// Known-answer vectors for the classic OpenVPN key-method-2 key derivation —
// the only test here that can tell a correct PRF from a convincing wrong one.
//
// testdata/vectors.json was captured from a real OpenVPN 2.4.12 peer: an
// instrumented build dumps the inputs and output of generate_key_expansion()
// (src/openvpn/ssl.c), and two containers of it complete a handshake so the two
// dumps can be compared. See docker/PRF-VECTORS.md.
package prf_test

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"testing"

	"github.com/buengese/go-openvpn/internal/prf"
)

// vectorsPath is the captured ground truth, relative to this package.
const vectorsPath = "testdata/vectors.json"

// vectorFile is testdata/vectors.json.
type vectorFile struct {
	Provenance struct {
		CapturedAt           string   `json:"captured_at"`
		OpenVPNVersion       string   `json:"openvpn_version"`
		Image                string   `json:"image"`
		Patch                string   `json:"patch"`
		InstrumentedFunction string   `json:"instrumented_function"`
		Derivation           []string `json:"derivation"`
	} `json:"provenance"`
	Vectors []vector `json:"vectors"`
}

// vector is one captured handshake: everything the two-stage derivation
// consumed, and the 256-byte key block it produced.
type vector struct {
	Name   string `json:"name"`
	Cipher string `json:"cipher"`
	Digest string `json:"digest"`
	Proto  string `json:"proto"`

	// Client material. PreMaster is generated by the client only; the
	// server's own key_source carries no pre_master (OpenVPN 2.4
	// src/openvpn/ssl.c, key_source2_randomize_write()).
	ClientPreMaster string `json:"client_pre_master"`
	ClientRandom1   string `json:"client_random1"`
	ClientRandom2   string `json:"client_random2"`

	// Server material.
	ServerRandom1 string `json:"server_random1"`
	ServerRandom2 string `json:"server_random2"`

	// The two 8-byte control-channel session IDs, which seed stage two.
	ClientSessionID string `json:"client_session_id"`
	ServerSessionID string `json:"server_session_id"`

	// MasterSecret is the 48-byte stage-one output. It is recorded so a
	// failure can be localised to one stage rather than to "the PRF".
	MasterSecret string `json:"master_secret"`

	// KeyBlock is the 256-byte stage-two output: the four 64-byte slots
	// described in prf.Slots, in order.
	KeyBlock string `json:"key_block"`
}

// loadVectors reads and decodes testdata/vectors.json.
func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	raw, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("read %s: %v", vectorsPath, err)
	}
	var vf vectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatalf("decode %s: %v", vectorsPath, err)
	}
	if len(vf.Vectors) == 0 {
		t.Fatalf("%s contains no vectors", vectorsPath)
	}
	return vf
}

// mustHex decodes a hex field and asserts its decoded length.
func mustHex(t *testing.T, field, s string, want int) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("%s: not hex: %v", field, err)
	}
	if len(b) != want {
		t.Fatalf("%s: %d bytes, want %d", field, len(b), want)
	}
	return b
}

// vectorInputs decodes one vector into the arguments the real API takes.
//
// PreMaster is set on the client alone, matching what the peers exchange: the
// server's key_source2 carries randoms only (OpenVPN 2.4 src/openvpn/ssl.c,
// key_source2_randomize_write()).
func vectorInputs(t *testing.T, v vector) (client, server prf.KeySource, clientSID, serverSID []byte) {
	t.Helper()
	client = prf.KeySource{
		PreMaster: mustHex(t, "client_pre_master", v.ClientPreMaster, 48),
		Random1:   mustHex(t, "client_random1", v.ClientRandom1, 32),
		Random2:   mustHex(t, "client_random2", v.ClientRandom2, 32),
	}
	server = prf.KeySource{
		Random1: mustHex(t, "server_random1", v.ServerRandom1, 32),
		Random2: mustHex(t, "server_random2", v.ServerRandom2, 32),
	}
	clientSID = mustHex(t, "client_session_id", v.ClientSessionID, 8)
	serverSID = mustHex(t, "server_session_id", v.ServerSessionID, 8)
	return client, server, clientSID, serverSID
}

// describeDiff summarises how a derived value differs from the recorded one:
// where it first diverges, how much diverges, and — for a 256-byte key block —
// which 64-byte slot the first difference lands in. A block wrong only in slots
// 2 and 3 is a different bug from one wrong from byte 0.
func describeDiff(got, want []byte) string {
	if len(got) != len(want) {
		return fmt.Sprintf("length %d, want %d", len(got), len(want))
	}
	first, differing := -1, 0
	for i := range want {
		if got[i] != want[i] {
			if first < 0 {
				first = i
			}
			differing++
		}
	}
	if first < 0 {
		return "identical"
	}
	s := fmt.Sprintf("%d of %d bytes differ, first at offset %d", differing, len(want), first)
	if len(want) == 256 {
		s += fmt.Sprintf(" (slot %d, byte %d within it)", first/64, first%64)
	}
	return s
}

// -------------------------------------------------------------------------
// Tests
// -------------------------------------------------------------------------

// TestKeyMethod2Vectors checks both stages of the derivation against ground
// truth captured from a real OpenVPN 2.4.12 peer. Each vector runs as two
// nested subtests so a failure names its stage, which is why master_secret is
// recorded at all: stage one diverging points at the PRF or its seed, while
// stage one passing and stage two failing narrows it to the second label, the
// second pair of randoms, or the session IDs.
func TestKeyMethod2Vectors(t *testing.T) {
	vf := loadVectors(t)
	for _, v := range vf.Vectors {
		t.Run(v.Name, func(t *testing.T) {
			client, server, clientSID, serverSID := vectorInputs(t, v)

			// Stage one: master = TLS1PRF(pre_master, "OpenVPN master
			// secret", client_random1 ‖ server_random1) -> 48 B.
			stageOneOK := t.Run("stage1_master_secret", func(t *testing.T) {
				want := mustHex(t, "master_secret", v.MasterSecret, 48)
				got, err := prf.DeriveMasterSecret(client, server)
				if err != nil {
					t.Fatalf("DeriveMasterSecret: %v", err)
				}
				if !bytes.Equal(got, want) {
					t.Fatalf("stage 1 diverged from OpenVPN %s: %s\n"+
						"  suspect the PRF itself (TLS 1.0 MD5+SHA1 split, not HMAC-SHA256 and\n"+
						"  not the TLS 1.2 PRF), the label \"OpenVPN master secret\", or the order\n"+
						"  of client_random1 ‖ server_random1\n"+
						"   got: %x\n  want: %x",
						vf.Provenance.OpenVPNVersion, describeDiff(got, want), got, want)
				}
			})

			// Stage two: key_block = TLS1PRF(master, "OpenVPN key expansion",
			// client_random2 ‖ server_random2 ‖ client_sid ‖ server_sid) -> 256 B.
			t.Run("stage2_key_block", func(t *testing.T) {
				if !stageOneOK {
					t.Skip("not evaluated: stage 1 already diverged and stage 2 " +
						"consumes its output — fix the master secret first")
				}
				want := mustHex(t, "key_block", v.KeyBlock, 256)
				got, err := prf.DeriveKeyBlock(client, server, clientSID, serverSID)
				if err != nil {
					t.Fatalf("DeriveKeyBlock: %v", err)
				}
				if !bytes.Equal(got, want) {
					t.Fatalf("stage 2 diverged (cipher=%s digest=%s proto=%s, captured from OpenVPN %s): %s\n"+
						"  stage 1 matched, so the PRF and the master secret are right;\n"+
						"  suspect the label \"OpenVPN key expansion\", the order of\n"+
						"  client_random2 ‖ server_random2, or the two 8-byte session IDs\n"+
						"  appended after them\n"+
						"   got: %x\n  want: %x",
						v.Cipher, v.Digest, v.Proto, vf.Provenance.OpenVPNVersion,
						describeDiff(got, want), got, want)
				}
			})
		})
	}
}

// TestVectorsAreWellFormed guards the captured testdata itself: it must stay
// loadable, correctly sized, and wide enough to be worth trusting. The floor —
// at least three vectors across at least two cipher/digest combinations — is
// enforced so that an edit cannot quietly narrow the ground truth.
func TestVectorsAreWellFormed(t *testing.T) {
	vf := loadVectors(t)

	if len(vf.Vectors) < 3 {
		t.Errorf("%d vectors, want at least 3", len(vf.Vectors))
	}
	if vf.Provenance.OpenVPNVersion == "" || vf.Provenance.Patch == "" ||
		vf.Provenance.Image == "" || vf.Provenance.CapturedAt == "" {
		t.Error("provenance is incomplete; a vector nobody can regenerate is not ground truth")
	}
	if len(vf.Provenance.Derivation) == 0 {
		t.Error("provenance records no derivation description")
	}

	combos := make(map[string]bool)
	blocks := make(map[string]string)
	for _, v := range vf.Vectors {
		t.Run(v.Name, func(t *testing.T) {
			mustHex(t, "client_pre_master", v.ClientPreMaster, 48)
			mustHex(t, "client_random1", v.ClientRandom1, 32)
			mustHex(t, "client_random2", v.ClientRandom2, 32)
			mustHex(t, "server_random1", v.ServerRandom1, 32)
			mustHex(t, "server_random2", v.ServerRandom2, 32)
			mustHex(t, "client_session_id", v.ClientSessionID, 8)
			mustHex(t, "server_session_id", v.ServerSessionID, 8)
			mustHex(t, "master_secret", v.MasterSecret, 48)
			mustHex(t, "key_block", v.KeyBlock, 256)

			if v.Cipher == "" || v.Digest == "" {
				t.Error("vector records no cipher/digest")
			}
		})
		combos[v.Cipher+"/"+v.Digest] = true
		if prev, dup := blocks[v.KeyBlock]; dup {
			t.Errorf("%s and %s recorded the same key block; ephemeral material must differ per handshake",
				prev, v.Name)
		}
		blocks[v.KeyBlock] = v.Name
	}

	if len(combos) < 2 {
		t.Errorf("%d cipher/digest combination(s), want at least 2", len(combos))
	}
}
