//go:build linux || android

// The route-table half of the redirect-gateway tests: these assert on the
// netlink messages routePlan and buildRouteMsg produce, not on the kernel's
// reaction to them, so they run unprivileged and pin the wire form.
package routing

import (
	"encoding/binary"
	"fmt"
	"net"
	"testing"

	"golang.org/x/sys/unix"
)

// decodedRoute is one netlink route message read back off the wire.
type decodedRoute struct {
	msgType uint16
	flags   uint16
	family  uint8
	dstLen  uint8
	scope   uint8
	dst     net.IP
	gw      net.IP
	oif     uint32
}

func (d decodedRoute) String() string {
	return fmt.Sprintf("%s/%d via %v oif %d", d.dst, d.dstLen, d.gw, d.oif)
}

// decodeRouteMsg parses a message built by buildRouteMsg back into its fields.
// It deliberately re-reads the bytes rather than trusting the routeSpec: the
// bytes are what the kernel would act on.
func decodeRouteMsg(t *testing.T, b []byte) decodedRoute {
	t.Helper()
	const rtmsgSize = 12
	if len(b) < nlmsgHdrSize+rtmsgSize {
		t.Fatalf("netlink message is %d bytes, too short for a route", len(b))
	}
	if got, want := binary.LittleEndian.Uint32(b[0:4]), uint32(len(b)); got > want {
		t.Errorf("nlmsg_len = %d but the message is %d bytes", got, want)
	}

	d := decodedRoute{
		msgType: binary.LittleEndian.Uint16(b[4:6]),
		flags:   binary.LittleEndian.Uint16(b[6:8]),
		family:  b[nlmsgHdrSize],
		dstLen:  b[nlmsgHdrSize+1],
		scope:   b[nlmsgHdrSize+6],
	}

	attrs := b[nlmsgHdrSize+rtmsgSize:]
	for len(attrs) >= 4 {
		attrLen := int(binary.LittleEndian.Uint16(attrs[0:2]))
		attrType := binary.LittleEndian.Uint16(attrs[2:4])
		if attrLen < 4 || attrLen > len(attrs) {
			break
		}
		val := attrs[4:attrLen]
		switch attrType {
		case unix.RTA_DST:
			d.dst = append(net.IP(nil), val...)
		case unix.RTA_GATEWAY:
			d.gw = append(net.IP(nil), val...)
		case unix.RTA_OIF:
			if len(val) >= 4 {
				d.oif = binary.LittleEndian.Uint32(val)
			}
		}
		aligned := (attrLen + 3) &^ 3
		if aligned > len(attrs) {
			break
		}
		attrs = attrs[aligned:]
	}
	return d
}

// decodePlan builds every message in a plan and decodes it.
func decodePlan(t *testing.T, plan []routeSpec) []decodedRoute {
	t.Helper()
	out := make([]decodedRoute, 0, len(plan))
	for i, s := range plan {
		msg, err := buildRouteMsg(s)
		if err != nil {
			t.Fatalf("buildRouteMsg(%d, %s): %v", i, s.what, err)
		}
		out = append(out, decodeRouteMsg(t, msg))
	}
	return out
}

const testIfIndex = 7

func redirectOpts(t *testing.T, reply string) *PushOptions {
	t.Helper()
	opts, err := ParsePushReply(reply)
	if err != nil {
		t.Fatalf("ParsePushReply(%q): %v", reply, err)
	}
	return opts
}

// TestRoutePlan_RedirectGatewayInstallsTwoHalves pins the two /1 halves: a
// single 0.0.0.0/0 sent with NLM_F_CREATE|NLM_F_EXCL fails with EEXIST on any
// host that already has a default route, which is every NetworkManager or
// systemd-networkd host (openvpn-2.6.22 src/openvpn/route.c:1072-1082).
func TestRoutePlan_RedirectGatewayInstallsTwoHalves(t *testing.T) {
	opts := redirectOpts(t, "PUSH_REPLY,topology subnet,ifconfig 10.8.0.6 255.255.255.0,"+
		"route-gateway 10.8.0.1,redirect-gateway def1")

	got := decodePlan(t, routePlan(opts, testIfIndex, true))
	if len(got) != 2 {
		t.Fatalf("plan is %v, want exactly the two /1 halves", got)
	}

	for _, d := range got {
		if d.dstLen == 0 {
			t.Errorf("%s is a 0.0.0.0/0; the reference never adds one beside the host's default", d)
		}
		if d.flags&unix.NLM_F_EXCL != 0 {
			t.Errorf("%s carries NLM_F_EXCL: an existing route would make this a silent no-op", d)
		}
		if d.flags&unix.NLM_F_REPLACE == 0 {
			t.Errorf("%s does not carry NLM_F_REPLACE, so it can still fail to install", d)
		}
		if d.msgType != unix.RTM_NEWROUTE {
			t.Errorf("%s is message type %d, want RTM_NEWROUTE", d, d.msgType)
		}
		if d.oif != testIfIndex {
			t.Errorf("%s leaves by interface %d, want the tunnel (%d)", d, d.oif, testIfIndex)
		}
		if !d.gw.Equal(net.IPv4(10, 8, 0, 1)) {
			t.Errorf("%s next hop is %v, want the pushed route-gateway 10.8.0.1", d, d.gw)
		}
		if d.dstLen != 1 {
			t.Errorf("%s is not a /1", d)
		}
	}
	if !got[0].dst.Equal(net.IPv4(0, 0, 0, 0)) || !got[1].dst.Equal(net.IPv4(128, 0, 0, 0)) {
		t.Errorf("halves are %s and %s, want 0.0.0.0/1 and 128.0.0.0/1", got[0], got[1])
	}
}

// TestRoutePlan_DeleteMirrorsApply pins that teardown removes exactly what
// bring-up installed. The two are generated by one function precisely so they
// cannot drift; this is the assertion that says so.
func TestRoutePlan_DeleteMirrorsApply(t *testing.T) {
	opts := redirectOpts(t, "PUSH_REPLY,topology subnet,ifconfig 10.8.0.6 255.255.255.0,"+
		"route-gateway 10.8.0.1,route 10.10.0.0 255.255.0.0,redirect-gateway def1")

	added := decodePlan(t, routePlan(opts, testIfIndex, true))
	removed := decodePlan(t, routePlan(opts, testIfIndex, false))
	if len(added) != len(removed) {
		t.Fatalf("apply installs %d routes, delete removes %d", len(added), len(removed))
	}
	for i := range added {
		if added[i].msgType != unix.RTM_NEWROUTE {
			t.Errorf("apply[%d] is message type %d, want RTM_NEWROUTE", i, added[i].msgType)
		}
		if removed[i].msgType != unix.RTM_DELROUTE {
			t.Errorf("delete[%d] is message type %d, want RTM_DELROUTE", i, removed[i].msgType)
		}
		if removed[i].flags&(unix.NLM_F_CREATE|unix.NLM_F_EXCL|unix.NLM_F_REPLACE) != 0 {
			t.Errorf("delete[%d] carries create/excl/replace flags: %#x", i, removed[i].flags)
		}
		if !added[i].dst.Equal(removed[i].dst) || added[i].dstLen != removed[i].dstLen ||
			!added[i].gw.Equal(removed[i].gw) || added[i].oif != removed[i].oif {
			t.Errorf("delete[%d] = %s does not match apply[%d] = %s", i, removed[i], i, added[i])
		}
	}
}

// TestRoutePlan_NoIPv4 pins that "!ipv4" reaches the route table: a server
// asking for an IPv6-only redirect must not get its IPv4 default covered.
func TestRoutePlan_NoIPv4(t *testing.T) {
	opts := redirectOpts(t, "PUSH_REPLY,topology subnet,ifconfig 10.8.0.6 255.255.255.0,"+
		"route-gateway 10.8.0.1,ifconfig-ipv6 fd00::2/64 fd00::1,redirect-gateway ipv6 !ipv4")

	for _, d := range decodePlan(t, routePlan(opts, testIfIndex, true)) {
		if d.family == unix.AF_INET {
			t.Errorf("%s is an IPv4 route, but the server pushed !ipv4", d)
		}
	}
}

// TestRoutePlan_RedirectGateway6 pins the IPv6 cover: four more-specific
// prefixes, replaced rather than created-exclusive, never a ::/0
// (openvpn-2.6.22 src/openvpn/init.c:1555-1566).
func TestRoutePlan_RedirectGateway6(t *testing.T) {
	opts := redirectOpts(t, "PUSH_REPLY,ifconfig-ipv6 fd00::2/64 fd00::1,redirect-gateway ipv6 !ipv4")

	got := decodePlan(t, routePlan(opts, testIfIndex, true))
	if len(got) != 4 {
		t.Fatalf("plan is %v, want the four IPv6 cover prefixes", got)
	}
	for _, d := range got {
		if d.family != unix.AF_INET6 {
			t.Errorf("%s is not an IPv6 route", d)
		}
		if d.dstLen == 0 {
			t.Errorf("%s is a ::/0; the cover must be more specific than the host's default", d)
		}
		if d.flags&unix.NLM_F_EXCL != 0 || d.flags&unix.NLM_F_REPLACE == 0 {
			t.Errorf("%s is not a replacement: flags %#x", d, d.flags)
		}
		if !d.gw.Equal(net.ParseIP("fd00::1")) {
			t.Errorf("%s next hop is %v, want the pushed ifconfig-ipv6 gateway fd00::1", d, d.gw)
		}
	}
}

// TestRoutePlan_PushedRoutesStayExclusive pins that only the redirect cover is
// a replacement: an ordinary pushed route already in the table identically is
// a tolerated no-op, which is what keeps a net30 peer route the kernel
// installed for us from failing bring-up.
func TestRoutePlan_PushedRoutesStayExclusive(t *testing.T) {
	opts := redirectOpts(t, "PUSH_REPLY,ifconfig 10.8.0.6 10.8.0.5,route 10.10.0.0 255.255.0.0")

	plan := routePlan(opts, testIfIndex, true)
	if len(plan) != 2 {
		t.Fatalf("plan has %d entries, want the peer host route and the pushed route", len(plan))
	}
	for i, s := range plan {
		if s.flags != unix.NLM_F_CREATE|unix.NLM_F_EXCL {
			t.Errorf("plan[%d] (%s) flags %#x, want CREATE|EXCL", i, s.what, s.flags)
		}
		if s.tolerate != unix.EEXIST {
			t.Errorf("plan[%d] (%s) does not tolerate EEXIST", i, s.what)
		}
	}
}

// TestRoutePlan_SkipsRoutesAroundTheTunnel pins that a net_gateway or
// remote_host next hop is not sent to the tunnel's own gateway.
func TestRoutePlan_SkipsRoutesAroundTheTunnel(t *testing.T) {
	opts := redirectOpts(t, "PUSH_REPLY,topology subnet,ifconfig 10.8.0.6 255.255.255.0,"+
		"route-gateway 10.8.0.1,route 192.168.1.0 255.255.255.0 net_gateway,"+
		"route 10.10.0.0 255.255.0.0")

	got := decodePlan(t, routePlan(opts, testIfIndex, true))
	for _, d := range got {
		if d.dst.Equal(net.IPv4(192, 168, 1, 0)) {
			t.Errorf("%s was installed, but net_gateway means around the tunnel", d)
		}
	}
	if len(got) != 1 {
		t.Errorf("plan is %v, want only the ordinary pushed route", got)
	}
}

// TestBuildRouteMsg_RejectsNonContiguousMask pins that a mask the kernel could
// not express does not silently become a /0. net.IPMask.Size reports (0, 0)
// for a non-contiguous mask, which would otherwise read as a default route.
func TestBuildRouteMsg_RejectsNonContiguousMask(t *testing.T) {
	s := routeSpec{
		msgType: unix.RTM_NEWROUTE,
		family:  unix.AF_INET,
		dst:     net.IPv4(10, 0, 0, 0),
		mask:    net.IPMask{255, 0, 255, 0},
		what:    "non-contiguous",
	}
	if _, err := buildRouteMsg(s); err == nil {
		t.Error("a non-contiguous mask must be refused, not sent as a /0")
	}
}

// TestBypassSpecFollowsTheServerAddressFamily pins that the host route keeping
// the control channel outside the tunnel is built for the family the transport
// dialed: an IPv6 server under redirect-gateway ipv6 needs a /128 bypass, or
// the cover routes capture the connection carrying them.
func TestBypassSpecFollowsTheServerAddressFamily(t *testing.T) {
	for _, tc := range []struct {
		name       string
		serverIP   string
		wantFamily uint8
		wantBits   int
	}{
		{"IPv4 server", "203.0.113.9", unix.AF_INET, 32},
		{"IPv6 server", "2001:db8::9", unix.AF_INET6, 128},
	} {
		t.Run(tc.name, func(t *testing.T) {
			spec := bypassSpec(unix.RTM_NEWROUTE, 0, net.ParseIP(tc.serverIP), net.ParseIP("192.0.2.1"))
			if spec.family != tc.wantFamily {
				t.Errorf("family = %d, want %d", spec.family, tc.wantFamily)
			}
			if ones, bits := spec.mask.Size(); ones != tc.wantBits || bits != tc.wantBits {
				t.Errorf("mask = /%d of %d, want a /%d host route", ones, bits, tc.wantBits)
			}
		})
	}
}

// TestParseRouteGatewayKeepsAWholeIPv6Address covers the attribute width: an
// RTA_GATEWAY is 4 bytes for an IPv4 next hop and 16 for an IPv6 one, and a
// fixed 4-byte copy would truncate every v6 gateway to its first quad.
func TestParseRouteGatewayKeepsAWholeIPv6Address(t *testing.T) {
	want := net.ParseIP("fe80::1")
	got, err := parseRouteGateway(buildFakeRouteReply(want))
	if err != nil {
		t.Fatalf("parseRouteGateway: %v", err)
	}
	if !got.Equal(want) {
		t.Errorf("gateway = %v, want %v", got, want)
	}
}
